version: '3.6'
services:
  mysql:
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
  
  redis:
    image: redis:4.0.9-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis

  rails:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379
    command: bash -c "rm -f /app/tmp/pids/server.pid || true && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    stdin_open: true
    tty: true

volumes:
  mysql-volume:
