version: "3.6"
services:
  mysql:
    image: mysql:5.7.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql

  redis:
    image: redis:4.0.9-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - "redis:/data"

  rails:
    build:
      context: .
    command: bash -c "rm -f /app/tmp/pids/server.pid || true && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    stdin_open: true
    tty: true
    env_file:
      - ".env"

  cable:
    build:
      context: .
    depends_on:
      - rails
      - redis
    command: puma -p 28080 /app/cable/config.ru
    ports:
      - "28080:28080"
    volumes:
      - ".:/app"
    env_file:
      - ".env"

volumes:
  redis:
  mysql-volume:
