default: &default
  adapter: mysql2
  encoding: utf8
  pool: 25
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'root' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { nil } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 3306 } %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { 'selfie_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME') { 'selfie_test' } %>

production:
  <<: *default
  database: selfie_production
  username: selfie
  password: <%= ENV['selfie_DATABASE_PASSWORD'] %>
